In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("광진구식품위생업소행정처분현황.csv", encoding="utf-8")

print("데이터 shape : ",data.shape)
# display(data.isna())
display(data.head())

데이터 shape :  (14565, 18)

,시군구코드,처분일자,교부번호,업종명,업태명,업소명,소재지도로명,소재지지번,지도점검일자,행정처분상태,처분명,법적근거,위반일자,위반내용,처분내용,처분기간,영업장면적(㎡),운영형태
0,3040000,19940829,19740039004,일반음식점,한식,풍차집,NaN,서울특별시 광진구 광장동 산 189번지 30호,19940829.0,처분확정,(),NaN,19940829,(),(),NaN,35.96,NaN
1,3040000,19950511,19740039004,일반음식점,한식,풍차집,NaN,서울특별시 광진구 광장동 산 189번지 30호,19950511.0,처분확정,(),NaN,19950511,(),(),15.0,35.96,NaN
2,3040000,19981105,19740039004,일반음식점,한식,풍차집,NaN,서울특별시 광진구 광장동 산 189번지 30호,19981105.0,처분확정,(),NaN,19981105,(),(),30.0,35.96,NaN
3,3040000,19940514,19750039002,일반음식점,한식,함부르크,NaN,서울특별시 광진구 화양동 산 212번지 0호,19940514.0,처분확정,(),NaN,19940514,(),(),0.0,128.72,NaN
4,3040000,19940829,19760039011,일반음식점,한식,버드나무집,NaN,서울특별시 광진구 광장동 산 319번지 1호,19940829.0,처분확정,(),NaN,19940829,(),(),0.0,628.10,NaN